#Init

In [2]:
import tensorflow as tf

#Build hypothesis and cost

In [14]:
x_data = [1, 2, 3, 4, 5]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable(2.9)
b = tf.Variable(0.5)

hypothesis = W * x_data + b

hypothesis

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 3.4     ,  6.3     ,  9.200001, 12.1     , 15.      ],
      dtype=float32)>

In [6]:
tf.square(hypothesis - y_data)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([  5.76    ,  18.490002,  38.44001 ,  65.61001 , 100.      ],
      dtype=float32)>

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - y_data))
cost

<tf.Tensor: shape=(), dtype=float32, numpy=45.660004>

#Gradient descent

In [29]:
learning_rate = 0.001

with tf.GradientTape() as tape:
  hypothesis = W * x_data + b
  print(hypothesis)

  cost = tf.reduce_mean(tf.square(hypothesis - y_data))
  print(cost)

W_grad, b_grad = tape.gradient(cost, [W, b])
print(W_grad, b_grad)

# A.assign_sub(B) => A -= B
W.assign_sub(learning_rate * W_grad)
b.assign_sub(learning_rate * b_grad)

W, b

tf.Tensor([ -3403933.2  -6069537.   -8735140.  -11400744.  -14066348. ], shape=(5,), dtype=float32)
tf.Tensor(90513626000000.0, shape=(), dtype=float32)
tf.Tensor(-63073284.0, shape=(), dtype=float32) tf.Tensor(-17470288.0, shape=(), dtype=float32)


(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-2602530.2>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-720859.44>)

In [31]:
W = tf.Variable(2.9)
b = tf.Variable(0.5)

for i in range(1000):
  with tf.GradientTape() as tape:
    hypothesis = W * x_data + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))

  W_grad, b_grad = tape.gradient(cost, [W, b])

  W.assign_sub(learning_rate * W_grad)
  b.assign_sub(learning_rate * b_grad)

  if i % 10 == 0:
    print("{:5}|{:10.4}|{:10.4}|{:10.6f}".format(i, W.numpy(), b.numpy(), cost))

    0|     2.855|    0.4876| 45.660004
   10|     2.462|    0.3787| 28.284033
   20|     2.152|    0.2929| 17.520519
   30|     1.908|    0.2255| 10.853079
   40|     1.716|    0.1724|  6.722954
   50|     1.565|    0.1306|  4.164561
   60|     1.446|    0.0978|  2.579767
   70|     1.352|   0.07196|  1.598069
   80|     1.279|   0.05165|  0.989959
   90|     1.221|   0.03567|  0.613266
  100|     1.175|   0.02312|  0.379924
  110|     1.139|   0.01325|  0.235381
  120|     1.111|  0.005506|  0.145844
  130|     1.089|-0.0005743|  0.090380
  140|     1.071| -0.005344|  0.056023
  150|     1.057| -0.009081|  0.034740
  160|     1.046|  -0.01201|  0.021556
  170|     1.038|  -0.01429|  0.013389
  180|     1.031|  -0.01607|  0.008330
  190|     1.026|  -0.01746|  0.005196
  200|     1.022|  -0.01854|  0.003254
  210|     1.018|  -0.01937|  0.002051
  220|     1.016|     -0.02|  0.001306
  230|     1.014|  -0.02049|  0.000844
  240|     1.012|  -0.02085|  0.000557
  250|     1.011|  -0.021