#Init

In [10]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt


In [11]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [12]:
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3

In [13]:
W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

variables = [W, b]
variables

[<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.5042709 , -0.5445337 , -0.6094761 ],
        [-0.37576157, -0.4226177 ,  0.6547103 ],
        [ 0.01105409,  0.8888413 , -0.0913555 ],
        [-0.48007274, -1.5596874 , -1.2194515 ]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 1.475458  , -0.76861066,  2.5081992 ], dtype=float32)>]

In [14]:
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[2.4104345e-01 6.6629630e-03 7.5229365e-01]
 [8.6044562e-01 1.7168025e-02 1.2238637e-01]
 [9.8867899e-01 7.9766562e-04 1.0523364e-02]
 [9.9808854e-01 5.5463827e-04 1.3567952e-03]
 [5.0985649e-02 4.9735128e-04 9.4851708e-01]
 [9.4735086e-01 3.9682770e-03 4.8680872e-02]
 [2.5845572e-01 2.1592260e-03 7.3938507e-01]
 [2.2414684e-01 1.4603006e-03 7.7439290e-01]], shape=(8, 3), dtype=float32)


In [15]:
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[9.9985957e-01 7.0221205e-07 1.3965195e-04]], shape=(1, 3), dtype=float32)


In [16]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(3.8025842, shape=(), dtype=float32)


In [17]:
x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = x * x # x^2
dy_dx = g.gradient(y, x) # Will compute to 6.0
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


##Gradient Function

In [18]:
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)

        return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.0501581 , -0.74328804, -0.30687007],
       [-0.537417  , -1.2416947 ,  1.7791119 ],
       [ 0.7362882 , -1.8613951 ,  1.125107  ],
       [ 0.8707362 , -1.9879453 ,  1.1172093 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.32114947, -0.37084144,  0.04969201], dtype=float32)>]


In [19]:
def fit(X, Y, epochs=2000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1: 2.188940
Loss at epoch 100: 0.647073
Loss at epoch 200: 0.573649
Loss at epoch 300: 0.522209
Loss at epoch 400: 0.479337
Loss at epoch 500: 0.441097
Loss at epoch 600: 0.405656
Loss at epoch 700: 0.371765
Loss at epoch 800: 0.338333
Loss at epoch 900: 0.304333
Loss at epoch 1000: 0.269077
Loss at epoch 1100: 0.236079
Loss at epoch 1200: 0.221018
Loss at epoch 1300: 0.210778
Loss at epoch 1400: 0.201408
Loss at epoch 1500: 0.192804
Loss at epoch 1600: 0.184878
Loss at epoch 1700: 0.177554
Loss at epoch 1800: 0.170768
Loss at epoch 1900: 0.164465
Loss at epoch 2000: 0.158594


#Prediction

In [20]:
sample_data = [[2,1,3,2]] # answer_label [[0,0,1]]
sample_data = np.asarray(sample_data, dtype=np.float32)

a = hypothesis(sample_data)

print(a)
print(tf.argmax(a, 1)) #index: 2

tf.Tensor([[6.954472e-04 7.420425e-02 9.251003e-01]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [21]:
b = hypothesis(x_data)
print(b)
print(tf.argmax(b, 1))
print(tf.argmax(y_data, 1)) # matches with y_data

tf.Tensor(
[[4.4474009e-06 1.5241416e-03 9.9847144e-01]
 [6.9544686e-04 7.4204251e-02 9.2510033e-01]
 [3.3884401e-08 1.5877879e-01 8.4122115e-01]
 [4.0270058e-07 8.5805970e-01 1.4193989e-01]
 [2.6668507e-01 7.2196531e-01 1.1349678e-02]
 [1.4112115e-01 8.5857397e-01 3.0475788e-04]
 [7.4387211e-01 2.5603536e-01 9.2472692e-05]
 [9.1462535e-01 8.5372828e-02 1.9068535e-06]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
